version: "3.9"  # optional since v1.27.0
services:
  ms-a:
    image: ms-a
    build: 
      context: ./ms-a
      dockerfile: Dockerfile
    container_name: ms-a
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"

  ms-b:
    image: ms-b
    build: 
      context: ./ms-b
      dockerfile: Dockerfile
    container_name: ms-b
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - A_HOST=ms-a
      - A_PORT=80
    restart: "no"

  ms-c:
    image: ms-c
    build: 
      context: ./ms-c
      dockerfile: Dockerfile
    container_name: ms-c
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - B_HOST=ms-b
      - B_PORT=80
    restart: "no"